# Generated by Django 3.1.1 on 2020-10-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
