# Generated by Django 3.1.1 on 2020-10-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
