# Generated by Django 3.1.1 on 2020-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_auto_20201006_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateField(null=True),
        ),
    ]
