# Generated by Django 3.1.2 on 2020-11-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0010_noticia_resumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='conteudo',
            new_name='descricao',
        ),
    ]
